<?php

namespace AppBundle\Repository;

/**
 * ConfirmEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfirmEmailRepository extends \Doctrine\ORM\EntityRepository
{
}
